AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy Hugging Face Embedding Model to SageMaker Serverless for Amplify Gen 2'

Parameters:
  ModelName:
    Type: String
    Default: 'huggingface-embedding-model'
    Description: 'Name for the SageMaker model'

  EndpointName:
    Type: String
    Default: 'embedding-endpoint'
    Description: 'Name for the SageMaker endpoint'

  HuggingFaceModelId:
    Type: String
    Default: 'BAAI/bge-large-en-v1.5'
    Description: 'Hugging Face model ID from the Hub'

  MaxConcurrency:
    Type: Number
    Default: 20
    MinValue: 1
    MaxValue: 200
    Description: 'Maximum number of concurrent invocations for serverless endpoint'

  MemorySize:
    Type: Number
    Default: 4096
    AllowedValues: [1024, 2048, 3008, 4096, 5120, 6144]
    Description: 'Memory allocation in MB (1024-6144 MB)'

Resources:
  # IAM Role for SageMaker Model Execution
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-SageMakerRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'

  # SageMaker Model
  SageMakerModel:
    Type: AWS::SageMaker::Model
    Properties:
      ModelName: !Ref ModelName
      ExecutionRoleArn: !GetAtt SageMakerExecutionRole.Arn
      PrimaryContainer:
        Image: !Sub '763104351884.dkr.ecr.${AWS::Region}.amazonaws.com/huggingface-pytorch-inference:1.13.1-transformers4.26.0-cpu-py39-ubuntu20.04'
        Environment:
          HF_MODEL_ID: !Ref HuggingFaceModelId
          HF_TASK: 'feature-extraction'
          SAGEMAKER_CONTAINER_LOG_LEVEL: '20'
          SAGEMAKER_REGION: !Ref AWS::Region
          SAGEMAKER_SUBMIT_DIRECTORY: '/opt/ml/code'
      Tags:
        - Key: Environment
          Value: !Ref AWS::StackName
        - Key: Purpose
          Value: 'Embedding Model'

  # SageMaker Endpoint Configuration for Serverless
  EndpointConfiguration:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      EndpointConfigName: !Sub '${EndpointName}-config'
      ProductionVariants:
        - ModelName: !GetAtt SageMakerModel.ModelName
          VariantName: 'primary'
          # Remove instance-related properties for serverless
          ServerlessConfig:
            MaxConcurrency: !Ref MaxConcurrency
            MemorySizeInMB: !Ref MemorySize
            # Optional: Provisioned concurrency for reduced cold starts
            # ProvisionedConcurrency: 1
      Tags:
        - Key: Environment
          Value: !Ref AWS::StackName

  # SageMaker Endpoint
  SageMakerEndpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointName: !Ref EndpointName
      EndpointConfigName: !GetAtt EndpointConfiguration.EndpointConfigName
      Tags:
        - Key: Environment
          Value: !Ref AWS::StackName
        - Key: Purpose
          Value: 'Serverless Embedding Endpoint'

  # IAM Policy for Lambda to invoke SageMaker endpoint
  LambdaSageMakerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWS::StackName}-LambdaSageMakerPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sagemaker:InvokeEndpoint
            Resource: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint/${EndpointName}'
      Roles:
        - !Ref LambdaExecutionRole

  # Lambda Execution Role (for your Amplify function)
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-LambdaExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'

Outputs:
  # SageMaker Resources
  EndpointName:
    Description: 'Name of the SageMaker serverless endpoint'
    Value: !Ref SageMakerEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-EndpointName'

  EndpointArn:
    Description: 'ARN of the SageMaker serverless endpoint'
    Value: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint/${SageMakerEndpoint}'
    Export:
      Name: !Sub '${AWS::StackName}-EndpointArn'

  ModelName:
    Description: 'Name of the SageMaker model'
    Value: !GetAtt SageMakerModel.ModelName
    Export:
      Name: !Sub '${AWS::StackName}-ModelName'

  EndpointConfigName:
    Description: 'Name of the endpoint configuration'
    Value: !GetAtt EndpointConfiguration.EndpointConfigName
    Export:
      Name: !Sub '${AWS::StackName}-EndpointConfigName'

  # IAM Resources
  SageMakerExecutionRoleArn:
    Description: 'ARN of the SageMaker execution role'
    Value: !GetAtt SageMakerExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SageMakerRoleArn'

  LambdaExecutionRoleArn:
    Description: 'ARN of the Lambda execution role for invoking SageMaker'
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaRoleArn'

  # Endpoint URLs
  InvokeEndpointUrl:
    Description: 'URL for invoking the SageMaker serverless endpoint'
    Value: !Sub 'https://runtime.sagemaker.${AWS::Region}.amazonaws.com/endpoints/${SageMakerEndpoint}/invocations'
    Export:
      Name: !Sub '${AWS::StackName}-InvokeUrl'

  # Serverless Configuration
  MaxConcurrency:
    Description: 'Maximum concurrent invocations configured'
    Value: !Ref MaxConcurrency
    Export:
      Name: !Sub '${AWS::StackName}-MaxConcurrency'

  MemorySize:
    Description: 'Memory size in MB configured for serverless endpoint'
    Value: !Ref MemorySize
    Export:
      Name: !Sub '${AWS::StackName}-MemorySize'