AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Milvus Standalone on EC2 (Ubuntu)

Resources:
  MilvusSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Milvus Ports
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 19530
          ToPort: 19530
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 19121
          ToPort: 19121
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MilvusInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.large
      # Use Ubuntu 22.04 LTS AMI (for us-east-1). Replace with region-specific ID if needed.
      ImageId: ami-01f23391a59163da9
      KeyName: milvus-key-pair
      SecurityGroups:
        - !Ref MilvusSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
            VolumeType: gp3
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > /var/log/user-data.log 2>&1

          apt update -y
          apt install -y docker.io git curl wget

          systemctl enable docker
          systemctl start docker

          # Add ubuntu user to docker group
          usermod -aG docker ubuntu

          # Wait until Docker is ready
          until docker info >/dev/null 2>&1; do
            echo "Waiting for Docker to start..."
            sleep 2
          done

          # Install Docker Compose v2 as plugin
          mkdir -p /usr/local/lib/docker/cli-plugins
          curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
            -o /usr/local/lib/docker/cli-plugins/docker-compose
          chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

          # Set up Milvus
          mkdir -p /home/ubuntu/milvus
          cd /home/ubuntu/milvus

          wget https://github.com/milvus-io/milvus/releases/download/v2.5.13/milvus-standalone-docker-compose.yml \
            -O docker-compose.yml

          docker compose up -d

Outputs:
  InstancePublicIP:
    Value: !GetAtt MilvusInstance.PublicIp
    Description: Milvus EC2 IP address
